#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color

error() {
  local fmt="${RED}!!${NC} $1"; shift

  printf "$fmt\n" "$@"
}

report() {
  local fmt="${GREEN}==${NC} $1"; shift

  printf "$fmt\n" "$@"
}

note() {
  local fmt="${ORANGE}!!${NC} $1"; shift

  printf "$fmt\n" "$@"
}

info() {
  local fmt="${BLUE}--${NC} $1"; shift

  printf "$fmt\n" "$@"  
}


skipping() {
  local fmt="${BLUE}--${NC} Skipping $1"; shift

  printf "$fmt\n" "$@"  
}

marquee() {
  local fmt="${GREEN}$1${NC}"; shift

  printf "${GREEN}-------------------------------------${NC}\n"
  printf "$fmt\n" "$@"
  printf "${GREEN}-------------------------------------${NC}\n"
}

doing() {
  local fmt="${ORANGE}..${NC} $1"; shift

  printf "$fmt" "$@"  
}

doing_complete() {
  printf " - ${GREEN}complete${NC}\n"
}

report_service() {
  if $(echo "$1" | grep already &> /dev/null); then
    local fmt="${BLUE}--${NC} $1"; shift
  else
    local fmt="${GREEN}==${NC} $1"; shift
  fi

  printf "$fmt\n" "$@"
}
